/*
 * This source file was generated by the Gradle 'init' task
 */
package com.statseyes.studio;

import com.statseyes.studio.domain.config.ApplicationConfiguration;
import com.statseyes.studio.presentation.navigation.SectionNavigator;
import com.statseyes.studio.presentation.navigation.ViewManager;
import com.statseyes.studio.infrastructure.security.SessionAdapter;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.context.ConfigurableApplicationContext;

@SpringBootApplication
public class App extends Application{

    private ConfigurableApplicationContext springContext;
    private SessionAdapter userSession;

    @Override
    public void init(){

        String[] args = getParameters().getRaw().toArray(new String[0]);
        this.springContext = new SpringApplicationBuilder()
                .sources(App.class)
                .headless(false)
                .run(args);
        this.userSession = this.springContext.getBean(SessionAdapter.class);
    }

    @Override
    public void start(Stage primaryStage){

        // Create an instance of ViewManager with injection of dependency
        // so it can create a controller factory
        ViewManager viewManager = new ViewManager(
                this.springContext,
                this.userSession);

        // VERY IMPORTANT : Without this there is no navigation
        springContext.getBean(SectionNavigator.class).setViewManager(viewManager);

        // Create javafx scene
        Scene scene = new Scene(new StackPane());
        viewManager.setMainScene(scene);

        // Load login view at startup
        viewManager.navigateTo(ApplicationConfiguration.LOGIN_PATH.getValue());

        // Define title for native window and attach a scene graph to it
        primaryStage.setTitle(
                ApplicationConfiguration.TITLE.getValue()
        );
        primaryStage.setScene(scene);
        primaryStage.setWidth(1080);
        primaryStage.setHeight(920);
        primaryStage.show();
    }

    @Override
    public void stop(){

        // Before quiting clear user session
        if(userSession != null){
            userSession.clear();
        }

        // Before quiting javafx stop spring boot
        springContext.stop();
        System.out.println("application stopped...");
    }

    public static void main(String[] args) {
        launch(args);
    }
}
